# Generated by Django 3.2 on 2021-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
