# Generated by Django 3.2 on 2021-06-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Isavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableinfo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPeronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='Md Mahiuddin', max_length=50)),
                ('Address', models.CharField(default='Panchagarch', max_length=50)),
                ('Phone', models.CharField(default='+8801', max_length=50)),
                ('Email', models.CharField(default=' @gmail.com', max_length=50)),
                ('Github', models.CharField(max_length=150)),
                ('Linkdin', models.CharField(max_length=150)),
                ('BrithInfo', models.DateField()),
                ('Nationality', models.CharField(default='Bangladesh', max_length=50)),
                ('Langages', models.CharField(max_length=50)),
                ('availableinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='About.isavailable')),
            ],
        ),
    ]
