# Generated by Django 3.2 on 2021-07-11 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('FlineText', models.CharField(max_length=50)),
                ('LlineText', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Md Mahiuddin', max_length=50)),
                ('mycv', models.FileField(upload_to='Cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=150)),
                ('degreeName', models.CharField(max_length=50)),
                ('Joindate', models.DateField()),
                ('fieldtype', models.CharField(choices=[('0', 'Present'), ('1', 'End date')], default=0, max_length=1)),
                ('Present', models.CharField(blank=True, max_length=50, null=True)),
                ('Lastdate', models.DateField(blank=True, null=True)),
                ('shortDec', models.TextField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Expreance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Joindate', models.DateField()),
                ('fieldtype', models.CharField(choices=[('0', 'Present'), ('1', 'End date')], default=0, max_length=1)),
                ('Present', models.CharField(blank=True, max_length=50, null=True)),
                ('Lastdate', models.DateField(blank=True, null=True)),
                ('shortDec', models.TextField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Isavailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableinfo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(max_length=50)),
                ('SkillPercen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorPeronal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='Md Mahiuddin', max_length=50)),
                ('Address', models.CharField(default='Panchagarch', max_length=50)),
                ('Phone', models.CharField(default='+8801', max_length=50)),
                ('Email', models.CharField(default=' @gmail.com', max_length=50)),
                ('Github', models.CharField(max_length=150)),
                ('Linkdin', models.CharField(max_length=150)),
                ('BrithInfo', models.DateField()),
                ('Nationality', models.CharField(default='Bangladesh', max_length=50)),
                ('Langages', models.CharField(max_length=50)),
                ('shortDesc', models.TextField(default='', max_length=500)),
                ('availableinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='About.isavailable')),
            ],
        ),
    ]
