# Generated by Django 3.2 on 2021-06-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorperonal',
            name='shortDesc',
            field=models.TextField(default='', max_length=500),
        ),
    ]
