# Generated by Django 3.2 on 2021-06-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expreance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Joindate', models.DateField()),
                ('fieldtype', models.CharField(choices=[('0', 'Text'), ('1', 'Date')], default='0', max_length=1)),
                ('Present', models.CharField(blank=True, max_length=50)),
                ('Lastdate', models.DateField()),
            ],
        ),
    ]
