# Generated by Django 3.2 on 2021-06-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0005_expreance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expreance',
            name='Lastdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='expreance',
            name='fieldtype',
            field=models.CharField(choices=[('0', 'Present'), ('1', 'End date')], default='0', max_length=1),
        ),
    ]
