# Generated by Django 3.2 on 2021-06-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_auto_20210610_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expreance',
            name='fieldtype',
            field=models.CharField(choices=[('0', 'Present'), ('1', 'End date')], max_length=1),
        ),
    ]
