# Generated by Django 3.2 on 2021-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0007_alter_expreance_fieldtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expreance',
            name='Lastdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expreance',
            name='Present',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
