# Generated by Django 3.2 on 2021-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0009_alter_expreance_fieldtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=150)),
                ('degreeName', models.CharField(max_length=50)),
                ('Joindate', models.DateField()),
                ('fieldtype', models.CharField(choices=[('0', 'Present'), ('1', 'End date')], default=0, max_length=1)),
                ('Present', models.CharField(blank=True, max_length=50, null=True)),
                ('Lastdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
