# Generated by Django 3.2 on 2021-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0010_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='shortDec',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='expreance',
            name='shortDec',
            field=models.TextField(default='', max_length=250),
        ),
    ]
