# Generated by Django 3.2 on 2021-06-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0011_auto_20210611_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycv', models.FileField(upload_to='Cv/')),
            ],
        ),
    ]
