# Generated by Django 3.2 on 2021-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0012_cvupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvupload',
            name='name',
            field=models.CharField(default='Md Mahiuddin', max_length=50),
        ),
    ]
