# Generated by Django 3.2 on 2021-06-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=50)),
                ('ProjectTitle', models.CharField(max_length=150)),
                ('ClinentName', models.CharField(max_length=50)),
                ('LanguageUse', models.CharField(max_length=250)),
                ('ProjectUrl', models.CharField(max_length=250)),
                ('ProjectImage', models.ImageField(upload_to='portfolio/')),
                ('UploadOption', models.CharField(choices=[('0', 'Image'), ('1', 'Slider Image'), ('2', 'Online Video'), ('3', 'Local Video')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='portfolio/')),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.portfolio')),
            ],
        ),
    ]
