# Generated by Django 3.2 on 2021-06-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='LocalVideo',
            field=models.FileField(blank=True, upload_to='portfolio/video/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='OnlineVieoUrl',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
