# Generated by Django 3.2 on 2021-06-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20210611_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleimageupload',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='multipleimageupload',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Portfolio.portfolio'),
        ),
    ]
